
language: objective-c
os: osx
before_install:
- gem install xcpretty
osx_image: xcode11
xcode_project: MagicCards.xcworkspace
xcode_scheme: MagicCards
xcode_destination: platform=iOS Simulator,OS=10.0,name=iPhone 11
