platform :ios, '10.0'

target 'MagicCards' do
  use_frameworks!

  pod 'SnapKit', '~> 5.0.0'
  pod 'SwiftLint'

end

target 'MagicCardsSnapshotTests' do
  inherit! :search_paths

  pod 'Nimble-Snapshots'

end

target 'MagicCardsTests' do
  inherit! :search_paths
end