platform :ios, '10.0'

target 'MagicCards' do
  use_frameworks! :linkage => :static

  pod 'SnapKit', '~> 5.0.0'
  pod 'SwiftLint'

  target 'MagicCardsTests' do
    inherit! :search_paths
  end

  target 'MagicCardsSnapshotTests' do
    inherit! :search_paths

    pod 'Nimble-Snapshots'

  end

end
